version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.9.16-management
    ports:
      - ${RABBITMQ_QUEUE_PORT}:5672
      - ${RABBITMQ_UI_PORT}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbit_nework

  postgres:
    image: postgres:15
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rabbit_nework

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    ports:
      - "${OLLAMA_PORT}:11434"
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
    entrypoint: ["/app/ollama_entrypoint.sh"]
    volumes:
      - .:/app
    networks:
      - rabbit_nework
    
  
  fastapi:
    build: ./src
    ports:
      - "${FASTAPI_PORT}:5000"
    environment:
      DB_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    depends_on:
      - rabbitmq
      - postgres
      - ollama
    volumes:
      - ./src:/app
    networks:
      - rabbit_nework

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  rabbit_nework:
    driver: bridge
